# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelParams = [
    # "ahci.mobile_lpm_policy=1"
    # ata6 is the WDC mechanical drive; cap its SATA link at 3.0 Gbps.
    "libata.force=6:3.0"

    # Reserve the 4 KiB page containing the Memtest error at physical 0x00038d903130.
    # Excluded range: 0x38d903000-0x38d903fff; takes effect after reboot.
    "memmap=4K$0x38d903000"
  ];
  # Bootloader.
  boot.loader = {
    systemd-boot = {
      enable = false;
      configurationLimit = 5;
    };
    limine = {
      enable = true;
      maxGenerations = 5;
      extraEntries = ''
        /:Windows 11
        comment: Windows 11
        protocol: efi
        path: boot():/EFI/Microsoft/Boot/bootmgfw.efi

        /:Memtest86+
        comment: Memory diagnostic
        protocol: efi
        path: boot():/EFI/memtest86plus/memtest86plus.efi
      '';
    };
    efi.canTouchEfiVariables = true;
    # grub.configurationLimit = 5;
  };

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/69f6ac99-2549-4106-923e-48efed92df1f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A5EB-573A";
    fsType = "vfat";
    # Restrict access to the EFI partition, including the boot loader random seed.
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/data" = {
    device = "/dev/disk/by-uuid/61d849b6-6a04-498f-bcf1-d01e47f3c6c4";
    fsType = "ext4";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fab12a13-7530-4a3c-9219-afa8234a9fee";
    fsType = "ext4";
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/142876759FFD4958";
    fsType = "ntfs-3g";
    options = [
      "rw"
      "uid=1000"
      "gid=100"
      "umask=022"
      "nofail"
    ];
  };

  # Managed swap file on the ext4 root filesystem (32 GiB).
  swapDevices = [
    {
      device = "/swapfile";
      size = 32768; # MiB
    }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
    nvidia = {
      modesetting.enable = true;
      open = true;
    };
  };
}
